# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TimelinesService_pb2 as TimelinesService__pb2


class TimelineServiceStub(object):
    """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/TimelinesService.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimelines = channel.unary_unary(
                '/PyGridWorld.TimelineService/GetTimelines',
                request_serializer=TimelinesService__pb2.TimelinesRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.TimelinesResponse.FromString,
                )
        self.GetTimelineTicks = channel.unary_unary(
                '/PyGridWorld.TimelineService/GetTimelineTicks',
                request_serializer=TimelinesService__pb2.TimelineTicksRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.TimelineTicksResponse.FromString,
                )
        self.GetTimelineData = channel.unary_stream(
                '/PyGridWorld.TimelineService/GetTimelineData',
                request_serializer=TimelinesService__pb2.TimelineDataRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.TimelineDataResponse.FromString,
                )
        self.GetTimelineJson = channel.unary_stream(
                '/PyGridWorld.TimelineService/GetTimelineJson',
                request_serializer=TimelinesService__pb2.TimelineJsonRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.TimelineJsonResponse.FromString,
                )
        self.GetTimelineEvents = channel.unary_stream(
                '/PyGridWorld.TimelineService/GetTimelineEvents',
                request_serializer=TimelinesService__pb2.TimelineEventsRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.TimelineEventsResponse.FromString,
                )
        self.GetOrStartSimulation = channel.unary_unary(
                '/PyGridWorld.TimelineService/GetOrStartSimulation',
                request_serializer=TimelinesService__pb2.GetOrStartSimulationRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.GetOrStartSimulationResponse.FromString,
                )
        self.StopSimulation = channel.unary_unary(
                '/PyGridWorld.TimelineService/StopSimulation',
                request_serializer=TimelinesService__pb2.StopSimulationRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.StopSimulationResponse.FromString,
                )
        self.MoveSimToTick = channel.unary_unary(
                '/PyGridWorld.TimelineService/MoveSimToTick',
                request_serializer=TimelinesService__pb2.MoveSimToTickRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.MoveSimToTickResponse.FromString,
                )
        self.EditSimulation = channel.stream_stream(
                '/PyGridWorld.TimelineService/EditSimulation',
                request_serializer=TimelinesService__pb2.EditSimulationRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.EditSimulationResponse.FromString,
                )
        self.GetTimelineTags = channel.unary_unary(
                '/PyGridWorld.TimelineService/GetTimelineTags',
                request_serializer=TimelinesService__pb2.GetTimelineTagsRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.GetTimelineTagsResponse.FromString,
                )
        self.ModifyTimelineTags = channel.unary_unary(
                '/PyGridWorld.TimelineService/ModifyTimelineTags',
                request_serializer=TimelinesService__pb2.ModifyTimelineTagsRequest.SerializeToString,
                response_deserializer=TimelinesService__pb2.ModifyTimelineTagsResponse.FromString,
                )


class TimelineServiceServicer(object):
    """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/TimelinesService.proto

    """

    def GetTimelines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineTicks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrStartSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveSimToTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditSimulation(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyTimelineTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimelineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimelines': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelines,
                    request_deserializer=TimelinesService__pb2.TimelinesRequest.FromString,
                    response_serializer=TimelinesService__pb2.TimelinesResponse.SerializeToString,
            ),
            'GetTimelineTicks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelineTicks,
                    request_deserializer=TimelinesService__pb2.TimelineTicksRequest.FromString,
                    response_serializer=TimelinesService__pb2.TimelineTicksResponse.SerializeToString,
            ),
            'GetTimelineData': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTimelineData,
                    request_deserializer=TimelinesService__pb2.TimelineDataRequest.FromString,
                    response_serializer=TimelinesService__pb2.TimelineDataResponse.SerializeToString,
            ),
            'GetTimelineJson': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTimelineJson,
                    request_deserializer=TimelinesService__pb2.TimelineJsonRequest.FromString,
                    response_serializer=TimelinesService__pb2.TimelineJsonResponse.SerializeToString,
            ),
            'GetTimelineEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTimelineEvents,
                    request_deserializer=TimelinesService__pb2.TimelineEventsRequest.FromString,
                    response_serializer=TimelinesService__pb2.TimelineEventsResponse.SerializeToString,
            ),
            'GetOrStartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrStartSimulation,
                    request_deserializer=TimelinesService__pb2.GetOrStartSimulationRequest.FromString,
                    response_serializer=TimelinesService__pb2.GetOrStartSimulationResponse.SerializeToString,
            ),
            'StopSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulation,
                    request_deserializer=TimelinesService__pb2.StopSimulationRequest.FromString,
                    response_serializer=TimelinesService__pb2.StopSimulationResponse.SerializeToString,
            ),
            'MoveSimToTick': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveSimToTick,
                    request_deserializer=TimelinesService__pb2.MoveSimToTickRequest.FromString,
                    response_serializer=TimelinesService__pb2.MoveSimToTickResponse.SerializeToString,
            ),
            'EditSimulation': grpc.stream_stream_rpc_method_handler(
                    servicer.EditSimulation,
                    request_deserializer=TimelinesService__pb2.EditSimulationRequest.FromString,
                    response_serializer=TimelinesService__pb2.EditSimulationResponse.SerializeToString,
            ),
            'GetTimelineTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelineTags,
                    request_deserializer=TimelinesService__pb2.GetTimelineTagsRequest.FromString,
                    response_serializer=TimelinesService__pb2.GetTimelineTagsResponse.SerializeToString,
            ),
            'ModifyTimelineTags': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyTimelineTags,
                    request_deserializer=TimelinesService__pb2.ModifyTimelineTagsRequest.FromString,
                    response_serializer=TimelinesService__pb2.ModifyTimelineTagsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PyGridWorld.TimelineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimelineService(object):
    """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/TimelinesService.proto

    """

    @staticmethod
    def GetTimelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/GetTimelines',
            TimelinesService__pb2.TimelinesRequest.SerializeToString,
            TimelinesService__pb2.TimelinesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimelineTicks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/GetTimelineTicks',
            TimelinesService__pb2.TimelineTicksRequest.SerializeToString,
            TimelinesService__pb2.TimelineTicksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimelineData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PyGridWorld.TimelineService/GetTimelineData',
            TimelinesService__pb2.TimelineDataRequest.SerializeToString,
            TimelinesService__pb2.TimelineDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimelineJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PyGridWorld.TimelineService/GetTimelineJson',
            TimelinesService__pb2.TimelineJsonRequest.SerializeToString,
            TimelinesService__pb2.TimelineJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimelineEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/PyGridWorld.TimelineService/GetTimelineEvents',
            TimelinesService__pb2.TimelineEventsRequest.SerializeToString,
            TimelinesService__pb2.TimelineEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrStartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/GetOrStartSimulation',
            TimelinesService__pb2.GetOrStartSimulationRequest.SerializeToString,
            TimelinesService__pb2.GetOrStartSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/StopSimulation',
            TimelinesService__pb2.StopSimulationRequest.SerializeToString,
            TimelinesService__pb2.StopSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveSimToTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/MoveSimToTick',
            TimelinesService__pb2.MoveSimToTickRequest.SerializeToString,
            TimelinesService__pb2.MoveSimToTickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EditSimulation(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/PyGridWorld.TimelineService/EditSimulation',
            TimelinesService__pb2.EditSimulationRequest.SerializeToString,
            TimelinesService__pb2.EditSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTimelineTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/GetTimelineTags',
            TimelinesService__pb2.GetTimelineTagsRequest.SerializeToString,
            TimelinesService__pb2.GetTimelineTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ModifyTimelineTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PyGridWorld.TimelineService/ModifyTimelineTags',
            TimelinesService__pb2.ModifyTimelineTagsRequest.SerializeToString,
            TimelinesService__pb2.ModifyTimelineTagsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
