# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import TimelinesService_pb2 as TimelinesService__pb2


class TimelineServiceStub(object):
  """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/TimelinesService.proto

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetTimelineTicks = channel.unary_unary(
        '/TimelineService/GetTimelineTicks',
        request_serializer=TimelinesService__pb2.TimelineTicksRequest.SerializeToString,
        response_deserializer=TimelinesService__pb2.TimelineTicksResponse.FromString,
        )
    self.GetTimelineData = channel.unary_stream(
        '/TimelineService/GetTimelineData',
        request_serializer=TimelinesService__pb2.TimelineDataRequest.SerializeToString,
        response_deserializer=TimelinesService__pb2.TimelineDataResponse.FromString,
        )
    self.GetTimelineJson = channel.unary_stream(
        '/TimelineService/GetTimelineJson',
        request_serializer=TimelinesService__pb2.TimelineJsonRequest.SerializeToString,
        response_deserializer=TimelinesService__pb2.TimelineJsonResponse.FromString,
        )


class TimelineServiceServicer(object):
  """python -m grpc_tools.protoc -I./protos --python_out=. --grpc_python_out=. ./protos/TimelinesService.proto

  """

  def GetTimelineTicks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTimelineData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTimelineJson(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TimelineServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetTimelineTicks': grpc.unary_unary_rpc_method_handler(
          servicer.GetTimelineTicks,
          request_deserializer=TimelinesService__pb2.TimelineTicksRequest.FromString,
          response_serializer=TimelinesService__pb2.TimelineTicksResponse.SerializeToString,
      ),
      'GetTimelineData': grpc.unary_stream_rpc_method_handler(
          servicer.GetTimelineData,
          request_deserializer=TimelinesService__pb2.TimelineDataRequest.FromString,
          response_serializer=TimelinesService__pb2.TimelineDataResponse.SerializeToString,
      ),
      'GetTimelineJson': grpc.unary_stream_rpc_method_handler(
          servicer.GetTimelineJson,
          request_deserializer=TimelinesService__pb2.TimelineJsonRequest.FromString,
          response_serializer=TimelinesService__pb2.TimelineJsonResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'TimelineService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
