# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TimelinesService.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TimelinesService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16TimelinesService.proto\"+\n\x14TimelineTicksRequest\x12\x13\n\x0btimeline_id\x18\x01 \x01(\x05\"%\n\x15TimelineTicksResponse\x12\x0c\n\x04tick\x18\x01 \x03(\x03\"8\n\x13TimelineDataRequest\x12\x13\n\x0btimeline_id\x18\x01 \x01(\x05\x12\x0c\n\x04tick\x18\x02 \x01(\x03\"$\n\x14TimelineDataResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\x98\x01\n\x0fTimelineService\x12\x43\n\x10GetTimelineTicks\x12\x15.TimelineTicksRequest\x1a\x16.TimelineTicksResponse\"\x00\x12@\n\x0fGetTimelineData\x12\x14.TimelineDataRequest\x1a\x15.TimelineDataResponse\"\x00\x62\x06proto3')
)




_TIMELINETICKSREQUEST = _descriptor.Descriptor(
  name='TimelineTicksRequest',
  full_name='TimelineTicksRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeline_id', full_name='TimelineTicksRequest.timeline_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)


_TIMELINETICKSRESPONSE = _descriptor.Descriptor(
  name='TimelineTicksResponse',
  full_name='TimelineTicksResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticks', full_name='TimelineTicksResponse.ticks', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=108,
)


_TIMELINEDATAREQUEST = _descriptor.Descriptor(
  name='TimelineDataRequest',
  full_name='TimelineDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeline_id', full_name='TimelineDataRequest.timeline_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tick', full_name='TimelineDataRequest.tick', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=166,
)


_TIMELINEDATARESPONSE = _descriptor.Descriptor(
  name='TimelineDataResponse',
  full_name='TimelineDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='TimelineDataResponse.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=204,
)

DESCRIPTOR.message_types_by_name['TimelineTicksRequest'] = _TIMELINETICKSREQUEST
DESCRIPTOR.message_types_by_name['TimelineTicksResponse'] = _TIMELINETICKSRESPONSE
DESCRIPTOR.message_types_by_name['TimelineDataRequest'] = _TIMELINEDATAREQUEST
DESCRIPTOR.message_types_by_name['TimelineDataResponse'] = _TIMELINEDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimelineTicksRequest = _reflection.GeneratedProtocolMessageType('TimelineTicksRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINETICKSREQUEST,
  __module__ = 'TimelinesService_pb2'
  # @@protoc_insertion_point(class_scope:TimelineTicksRequest)
  ))
_sym_db.RegisterMessage(TimelineTicksRequest)

TimelineTicksResponse = _reflection.GeneratedProtocolMessageType('TimelineTicksResponse', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINETICKSRESPONSE,
  __module__ = 'TimelinesService_pb2'
  # @@protoc_insertion_point(class_scope:TimelineTicksResponse)
  ))
_sym_db.RegisterMessage(TimelineTicksResponse)

TimelineDataRequest = _reflection.GeneratedProtocolMessageType('TimelineDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINEDATAREQUEST,
  __module__ = 'TimelinesService_pb2'
  # @@protoc_insertion_point(class_scope:TimelineDataRequest)
  ))
_sym_db.RegisterMessage(TimelineDataRequest)

TimelineDataResponse = _reflection.GeneratedProtocolMessageType('TimelineDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _TIMELINEDATARESPONSE,
  __module__ = 'TimelinesService_pb2'
  # @@protoc_insertion_point(class_scope:TimelineDataResponse)
  ))
_sym_db.RegisterMessage(TimelineDataResponse)



_TIMELINESERVICE = _descriptor.ServiceDescriptor(
  name='TimelineService',
  full_name='TimelineService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=207,
  serialized_end=359,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTimelineTicks',
    full_name='TimelineService.GetTimelineTicks',
    index=0,
    containing_service=None,
    input_type=_TIMELINETICKSREQUEST,
    output_type=_TIMELINETICKSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTimelineData',
    full_name='TimelineService.GetTimelineData',
    index=1,
    containing_service=None,
    input_type=_TIMELINEDATAREQUEST,
    output_type=_TIMELINEDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIMELINESERVICE)

DESCRIPTOR.services_by_name['TimelineService'] = _TIMELINESERVICE

# @@protoc_insertion_point(module_scope)
