# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from simma import simulation_pb2 as simma_dot_simulation__pb2


class SimulationStub(object):
    """python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. ./protos/simma/simulation.proto

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTick = channel.unary_unary(
                '/simma.Simulation/GetTick',
                request_serializer=simma_dot_simulation__pb2.GetTickRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetTickResponse.FromString,
                )
        self.GetStateJson = channel.unary_unary(
                '/simma.Simulation/GetStateJson',
                request_serializer=simma_dot_simulation__pb2.GetStateJsonRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetStateJsonResponse.FromString,
                )
        self.SetStateJson = channel.unary_unary(
                '/simma.Simulation/SetStateJson',
                request_serializer=simma_dot_simulation__pb2.SetStateJsonRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.SetStateJsonResponse.FromString,
                )
        self.CreateEntity = channel.unary_unary(
                '/simma.Simulation/CreateEntity',
                request_serializer=simma_dot_simulation__pb2.CreateEntityRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.CreateEntityResponse.FromString,
                )
        self.DestroyEntity = channel.unary_unary(
                '/simma.Simulation/DestroyEntity',
                request_serializer=simma_dot_simulation__pb2.DestroyEntityRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.DestroyEntityResponse.FromString,
                )
        self.GetAllEntities = channel.unary_unary(
                '/simma.Simulation/GetAllEntities',
                request_serializer=simma_dot_simulation__pb2.GetAllEntitiesRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetAllEntitiesResponse.FromString,
                )
        self.StartSimulation = channel.unary_unary(
                '/simma.Simulation/StartSimulation',
                request_serializer=simma_dot_simulation__pb2.StartSimulationRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.StartSimulationResponse.FromString,
                )
        self.StopSimulation = channel.unary_unary(
                '/simma.Simulation/StopSimulation',
                request_serializer=simma_dot_simulation__pb2.StopSimulationRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.StopSimulationResponse.FromString,
                )
        self.IsRunning = channel.unary_unary(
                '/simma.Simulation/IsRunning',
                request_serializer=simma_dot_simulation__pb2.IsRunningRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.IsRunningResponse.FromString,
                )
        self.AssignComponent = channel.unary_unary(
                '/simma.Simulation/AssignComponent',
                request_serializer=simma_dot_simulation__pb2.AssignComponentRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.AssignComponentResponse.FromString,
                )
        self.GetComponentJson = channel.unary_unary(
                '/simma.Simulation/GetComponentJson',
                request_serializer=simma_dot_simulation__pb2.GetComponentJsonRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetComponentJsonResponse.FromString,
                )
        self.RemoveComponent = channel.unary_unary(
                '/simma.Simulation/RemoveComponent',
                request_serializer=simma_dot_simulation__pb2.RemoveComponentRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.RemoveComponentResponse.FromString,
                )
        self.ReplaceComponent = channel.unary_unary(
                '/simma.Simulation/ReplaceComponent',
                request_serializer=simma_dot_simulation__pb2.ReplaceComponentRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.ReplaceComponentResponse.FromString,
                )
        self.GetComponentNames = channel.unary_unary(
                '/simma.Simulation/GetComponentNames',
                request_serializer=simma_dot_simulation__pb2.GetComponentNamesRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetComponentNamesResponse.FromString,
                )
        self.GetEntityComponentNames = channel.unary_unary(
                '/simma.Simulation/GetEntityComponentNames',
                request_serializer=simma_dot_simulation__pb2.GetEntityComponentNamesRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetEntityComponentNamesResponse.FromString,
                )
        self.GetSingletonJson = channel.unary_unary(
                '/simma.Simulation/GetSingletonJson',
                request_serializer=simma_dot_simulation__pb2.GetSingletonJsonRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetSingletonJsonResponse.FromString,
                )
        self.SetSingletonJson = channel.unary_unary(
                '/simma.Simulation/SetSingletonJson',
                request_serializer=simma_dot_simulation__pb2.SetSingletonJsonRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.SetSingletonJsonResponse.FromString,
                )
        self.GetSingletonNames = channel.unary_unary(
                '/simma.Simulation/GetSingletonNames',
                request_serializer=simma_dot_simulation__pb2.GetSingletonNamesRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetSingletonNamesResponse.FromString,
                )
        self.GetEvents = channel.unary_stream(
                '/simma.Simulation/GetEvents',
                request_serializer=simma_dot_simulation__pb2.GetEventsRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetEventsResponse.FromString,
                )
        self.GetStateBinary = channel.unary_unary(
                '/simma.Simulation/GetStateBinary',
                request_serializer=simma_dot_simulation__pb2.GetStateBinaryRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.GetStateBinaryResponse.FromString,
                )
        self.SetStateBinary = channel.unary_unary(
                '/simma.Simulation/SetStateBinary',
                request_serializer=simma_dot_simulation__pb2.SetStateBinaryRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.SetStateBinaryResponse.FromString,
                )
        self.RunCommand = channel.unary_unary(
                '/simma.Simulation/RunCommand',
                request_serializer=simma_dot_simulation__pb2.RunCommandRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.RunCommandResponse.FromString,
                )
        self.SetEditorToken = channel.unary_unary(
                '/simma.Simulation/SetEditorToken',
                request_serializer=simma_dot_simulation__pb2.SetEditorTokenRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.SetEditorTokenResponse.FromString,
                )
        self.IsEditing = channel.unary_unary(
                '/simma.Simulation/IsEditing',
                request_serializer=simma_dot_simulation__pb2.IsEditingRequest.SerializeToString,
                response_deserializer=simma_dot_simulation__pb2.IsEditingResponse.FromString,
                )


class SimulationServicer(object):
    """python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. ./protos/simma/simulation.proto

    """

    def GetTick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStateJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyEntity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllEntities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSimulation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsRunning(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComponentJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComponentNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntityComponentNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingletonJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSingletonJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSingletonNames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStateBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStateBinary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetEditorToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsEditing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTick': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTick,
                    request_deserializer=simma_dot_simulation__pb2.GetTickRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetTickResponse.SerializeToString,
            ),
            'GetStateJson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateJson,
                    request_deserializer=simma_dot_simulation__pb2.GetStateJsonRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetStateJsonResponse.SerializeToString,
            ),
            'SetStateJson': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStateJson,
                    request_deserializer=simma_dot_simulation__pb2.SetStateJsonRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.SetStateJsonResponse.SerializeToString,
            ),
            'CreateEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEntity,
                    request_deserializer=simma_dot_simulation__pb2.CreateEntityRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.CreateEntityResponse.SerializeToString,
            ),
            'DestroyEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyEntity,
                    request_deserializer=simma_dot_simulation__pb2.DestroyEntityRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.DestroyEntityResponse.SerializeToString,
            ),
            'GetAllEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllEntities,
                    request_deserializer=simma_dot_simulation__pb2.GetAllEntitiesRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetAllEntitiesResponse.SerializeToString,
            ),
            'StartSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSimulation,
                    request_deserializer=simma_dot_simulation__pb2.StartSimulationRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.StartSimulationResponse.SerializeToString,
            ),
            'StopSimulation': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSimulation,
                    request_deserializer=simma_dot_simulation__pb2.StopSimulationRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.StopSimulationResponse.SerializeToString,
            ),
            'IsRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.IsRunning,
                    request_deserializer=simma_dot_simulation__pb2.IsRunningRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.IsRunningResponse.SerializeToString,
            ),
            'AssignComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignComponent,
                    request_deserializer=simma_dot_simulation__pb2.AssignComponentRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.AssignComponentResponse.SerializeToString,
            ),
            'GetComponentJson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComponentJson,
                    request_deserializer=simma_dot_simulation__pb2.GetComponentJsonRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetComponentJsonResponse.SerializeToString,
            ),
            'RemoveComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveComponent,
                    request_deserializer=simma_dot_simulation__pb2.RemoveComponentRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.RemoveComponentResponse.SerializeToString,
            ),
            'ReplaceComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceComponent,
                    request_deserializer=simma_dot_simulation__pb2.ReplaceComponentRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.ReplaceComponentResponse.SerializeToString,
            ),
            'GetComponentNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComponentNames,
                    request_deserializer=simma_dot_simulation__pb2.GetComponentNamesRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetComponentNamesResponse.SerializeToString,
            ),
            'GetEntityComponentNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntityComponentNames,
                    request_deserializer=simma_dot_simulation__pb2.GetEntityComponentNamesRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetEntityComponentNamesResponse.SerializeToString,
            ),
            'GetSingletonJson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingletonJson,
                    request_deserializer=simma_dot_simulation__pb2.GetSingletonJsonRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetSingletonJsonResponse.SerializeToString,
            ),
            'SetSingletonJson': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSingletonJson,
                    request_deserializer=simma_dot_simulation__pb2.SetSingletonJsonRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.SetSingletonJsonResponse.SerializeToString,
            ),
            'GetSingletonNames': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSingletonNames,
                    request_deserializer=simma_dot_simulation__pb2.GetSingletonNamesRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetSingletonNamesResponse.SerializeToString,
            ),
            'GetEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.GetEvents,
                    request_deserializer=simma_dot_simulation__pb2.GetEventsRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetEventsResponse.SerializeToString,
            ),
            'GetStateBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStateBinary,
                    request_deserializer=simma_dot_simulation__pb2.GetStateBinaryRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.GetStateBinaryResponse.SerializeToString,
            ),
            'SetStateBinary': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStateBinary,
                    request_deserializer=simma_dot_simulation__pb2.SetStateBinaryRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.SetStateBinaryResponse.SerializeToString,
            ),
            'RunCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunCommand,
                    request_deserializer=simma_dot_simulation__pb2.RunCommandRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.RunCommandResponse.SerializeToString,
            ),
            'SetEditorToken': grpc.unary_unary_rpc_method_handler(
                    servicer.SetEditorToken,
                    request_deserializer=simma_dot_simulation__pb2.SetEditorTokenRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.SetEditorTokenResponse.SerializeToString,
            ),
            'IsEditing': grpc.unary_unary_rpc_method_handler(
                    servicer.IsEditing,
                    request_deserializer=simma_dot_simulation__pb2.IsEditingRequest.FromString,
                    response_serializer=simma_dot_simulation__pb2.IsEditingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simma.Simulation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Simulation(object):
    """python -m grpc_tools.protoc -I protos --python_out=. --grpc_python_out=. ./protos/simma/simulation.proto

    """

    @staticmethod
    def GetTick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetTick',
            simma_dot_simulation__pb2.GetTickRequest.SerializeToString,
            simma_dot_simulation__pb2.GetTickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetStateJson',
            simma_dot_simulation__pb2.GetStateJsonRequest.SerializeToString,
            simma_dot_simulation__pb2.GetStateJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStateJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/SetStateJson',
            simma_dot_simulation__pb2.SetStateJsonRequest.SerializeToString,
            simma_dot_simulation__pb2.SetStateJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/CreateEntity',
            simma_dot_simulation__pb2.CreateEntityRequest.SerializeToString,
            simma_dot_simulation__pb2.CreateEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DestroyEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/DestroyEntity',
            simma_dot_simulation__pb2.DestroyEntityRequest.SerializeToString,
            simma_dot_simulation__pb2.DestroyEntityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetAllEntities',
            simma_dot_simulation__pb2.GetAllEntitiesRequest.SerializeToString,
            simma_dot_simulation__pb2.GetAllEntitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/StartSimulation',
            simma_dot_simulation__pb2.StartSimulationRequest.SerializeToString,
            simma_dot_simulation__pb2.StartSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopSimulation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/StopSimulation',
            simma_dot_simulation__pb2.StopSimulationRequest.SerializeToString,
            simma_dot_simulation__pb2.StopSimulationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/IsRunning',
            simma_dot_simulation__pb2.IsRunningRequest.SerializeToString,
            simma_dot_simulation__pb2.IsRunningResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AssignComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/AssignComponent',
            simma_dot_simulation__pb2.AssignComponentRequest.SerializeToString,
            simma_dot_simulation__pb2.AssignComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetComponentJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetComponentJson',
            simma_dot_simulation__pb2.GetComponentJsonRequest.SerializeToString,
            simma_dot_simulation__pb2.GetComponentJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/RemoveComponent',
            simma_dot_simulation__pb2.RemoveComponentRequest.SerializeToString,
            simma_dot_simulation__pb2.RemoveComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplaceComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/ReplaceComponent',
            simma_dot_simulation__pb2.ReplaceComponentRequest.SerializeToString,
            simma_dot_simulation__pb2.ReplaceComponentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetComponentNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetComponentNames',
            simma_dot_simulation__pb2.GetComponentNamesRequest.SerializeToString,
            simma_dot_simulation__pb2.GetComponentNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntityComponentNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetEntityComponentNames',
            simma_dot_simulation__pb2.GetEntityComponentNamesRequest.SerializeToString,
            simma_dot_simulation__pb2.GetEntityComponentNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSingletonJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetSingletonJson',
            simma_dot_simulation__pb2.GetSingletonJsonRequest.SerializeToString,
            simma_dot_simulation__pb2.GetSingletonJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSingletonJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/SetSingletonJson',
            simma_dot_simulation__pb2.SetSingletonJsonRequest.SerializeToString,
            simma_dot_simulation__pb2.SetSingletonJsonResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSingletonNames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetSingletonNames',
            simma_dot_simulation__pb2.GetSingletonNamesRequest.SerializeToString,
            simma_dot_simulation__pb2.GetSingletonNamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/simma.Simulation/GetEvents',
            simma_dot_simulation__pb2.GetEventsRequest.SerializeToString,
            simma_dot_simulation__pb2.GetEventsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStateBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/GetStateBinary',
            simma_dot_simulation__pb2.GetStateBinaryRequest.SerializeToString,
            simma_dot_simulation__pb2.GetStateBinaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStateBinary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/SetStateBinary',
            simma_dot_simulation__pb2.SetStateBinaryRequest.SerializeToString,
            simma_dot_simulation__pb2.SetStateBinaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/RunCommand',
            simma_dot_simulation__pb2.RunCommandRequest.SerializeToString,
            simma_dot_simulation__pb2.RunCommandResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetEditorToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/SetEditorToken',
            simma_dot_simulation__pb2.SetEditorTokenRequest.SerializeToString,
            simma_dot_simulation__pb2.SetEditorTokenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsEditing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simma.Simulation/IsEditing',
            simma_dot_simulation__pb2.IsEditingRequest.SerializeToString,
            simma_dot_simulation__pb2.IsEditingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
